apiVersion: v1
kind: ConfigMap
metadata:
  name: mg-config
  
data:
  mongo_DB: mongodb
  mongo_USER: root
  mongo_PASSWORD: root123
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: mg-sc
provisioner: efs.csi.aws.com
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mg-pv1
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: mg-sc
  mountOptions:
    - tls
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0d6eaa867dd176c18
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mg-claim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: mg-sc
  resources:
    requests:
      storage: 1Gi
      
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: mongo
 labels:
   app: mongo
spec:
 replicas: 1
 selector:
   matchLabels:
     app: mongo
 template:
   metadata:
     labels:
       app: mongo
   spec:
     containers:
     - name: mongo
       image: mongo
       imagePullPolicy: "IfNotPresent"
       ports:
         - containerPort: 27017
       envFrom:
         - configMapRef:
             name: mg-config
       volumeMounts:
         - mountPath: /var/lib/mongodb/data
           name: mongodb
     volumes:
       - name: mongodb
         persistentVolumeClaim:
           claimName: mg-claim
